using System;
using YPrime.BusinessRule.Interfaces;

namespace YPrime.Core.BusinessLayer.Models
{
    [Serializable]
    public class BusinessRuleModel : IConfigModel, IBusinessRule
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string JSONBlob { get; set; }

        public bool Autogenerated { get; set; }
    }
}
