using System.Data.Entity.Migrations;
using System.Data.Entity.ModelConfiguration;
using YPrime.Data.Study.Constants;
using YPrime.Data.Study.Models;

namespace YPrime.Data.Study.Configurations.Entity
{
    public class SystemActionStudyRoleConfiguration
    {
        public SystemActionStudyRoleConfiguration(EntityTypeConfiguration<SystemActionStudyRole> entityConfiguration)
        {
        }

        public static void Seed(StudyDbContext context)
        {
            context.Database.ExecuteSqlCommand("PRINT 'System Action Seeding'");
            context.SystemActionStudyRoles.AddOrUpdate(s => new { s.StudyRoleId, s.SystemActionId },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanDownloadReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanAccessReviewerLandingPage },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewSiteManagement },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewPatientDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanSeePatientVisitList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewDashboard },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewReferenceMatieralList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanUseDeviceWidget },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanCreateExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanRunExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewAnalytics },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewReports },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewDiaryEntryDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanEditPatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanDownloadExportResults },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanSeePatientList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewDCFList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanViewDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanResetPatientPin },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.ClinicalResearchAssociate.Id, SystemActionId = SystemActionTypes.CanReviewPatientVisit },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanLoginToDevice },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanDownloadReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanAccessReviewerLandingPage },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanCreateDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanCreatePatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewPatientDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanSeePatientVisitList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewDashboard },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanEditPatient2 },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewReferenceMatieralList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanUseDeviceWidget },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewAnalytics },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewReports },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanCreateDCF },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewDiaryEntryDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanEditPatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanSeePatientList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewDCFList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanViewDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanResetPatientPin },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Investigator.Id, SystemActionId = SystemActionTypes.CanReviewPatientVisit },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanDownloadReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanAccessReviewerLandingPage },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewSiteManagement },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewPatientDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanSeePatientVisitList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewDashboard },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewReferenceMatieralList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanUseDeviceWidget },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanCreateExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanRunExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewAnalytics },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewReports },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewDiaryEntryDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanEditPatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanDownloadExportResults },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanSeePatientList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewDCFList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanViewDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanResetPatientPin },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.Sponsor.Id, SystemActionId = SystemActionTypes.CanReviewPatientVisit },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanLoginToDevice },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanDownloadReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanAccessReviewerLandingPage },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanCreateDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanCreatePatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewPatientDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanSeePatientVisitList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewDashboard },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanEditPatient2 },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewReferenceMatieralList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanUseDeviceWidget },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewAnalytics },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewReports },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanCreateDCF },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewDiaryEntryDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanEditPatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanSeePatientList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewDCFList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanViewDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanResetPatientPin },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.StudyCoordinator.Id, SystemActionId = SystemActionTypes.CanReviewPatientVisit },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanLoginToDevice },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanDownloadReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanAccessReviewerLandingPage },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanCreateDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanCreatePatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewPatientDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanSeePatientVisitList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewDashboard },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanEditPatient2 },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewReferenceMatieralList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanUseDeviceWidget },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewAnalytics },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewReports },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanCreateDCF },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewDiaryEntryDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanEditPatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanSeePatientList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewDCFList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanViewDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanResetPatientPin },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.SubInvestigator.Id, SystemActionId = SystemActionTypes.CanReviewPatientVisit },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanLoginToDevice },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanDownloadReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanAccessReviewerLandingPage },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanCreateDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanCreatePatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewSiteManagement },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.SiteBulkUpdate },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanRemoveVisitFromUser },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewPatientDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanSeePatientVisitList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanCreateBringYourOwnDeviceCode },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewDashboard },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanEditPatient2 },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewReferenceMatieralList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanUseDeviceWidget },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanCreateExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewSoftwareVersionManagement },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewUpcomingVisitsWidget },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanRunExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanEditSiteLanguages },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanAddEditSites },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewExport },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanCreateReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanAddVisitToUser },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewAnalytics },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewReports },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanCreateDCF },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewDiaryEntryDetails },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanEditPatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanDownloadExportResults },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanSeePatientList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewDCFList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanDeleteReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewRolesList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanImportSites },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewSoftwareReleases },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewConfirmationList },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanViewDataCorrections },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanResetPatientPin },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanReviewPatientVisit },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanUnblindPatient },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanUploadReferenceMaterials },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanCreateCaregiverInPortal },
                new SystemActionStudyRole() { StudyRoleId = Config.Defaults.StudyRoles.YP.Id, SystemActionId = SystemActionTypes.CanScheduleHangfireJobs }
            );

            context.SaveChanges();
        }
    }
}