// <auto-generated />
namespace YPrime.Data.Study.Configurations.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class diary_entry_software_release_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(diary_entry_software_release_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202102101512251_diary_entry_software_release_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
