namespace YPrime.Data.Study.Configurations.Context
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class OmniAuditReplacement : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AdditionalTablesToSync", "AuditUserID", c => c.String());
            AddColumn("dbo.AdditionalTablesToSync", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.AdditionalTablesToSync", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.Answer", "AuditUserID", c => c.String());
            AddColumn("dbo.Answer", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.Answer", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.AnswerScore", "AuditUserID", c => c.String());
            AddColumn("dbo.AnswerScore", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.AnswerScore", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.DiaryEntry", "AuditUserID", c => c.String());
            AddColumn("dbo.DiaryEntry", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.DiaryEntry", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.CareGiver", "AuditUserID", c => c.String());
            AddColumn("dbo.CareGiver", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CareGiver", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.Patient", "AuditUserID", c => c.String());
            AddColumn("dbo.Patient", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.Patient", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.Correction", "AuditUserID", c => c.String());
            AddColumn("dbo.Correction", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.Correction", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.CorrectionApprovalData", "AuditUserID", c => c.String());
            AddColumn("dbo.CorrectionApprovalData", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CorrectionApprovalData", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.CorrectionApprovalDataAdditional", "AuditUserID", c => c.String());
            AddColumn("dbo.CorrectionApprovalDataAdditional", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CorrectionApprovalDataAdditional", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.CorrectionDiscussion", "AuditUserID", c => c.String());
            AddColumn("dbo.CorrectionDiscussion", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CorrectionDiscussion", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.CorrectionAction", "AuditUserID", c => c.String());
            AddColumn("dbo.CorrectionAction", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CorrectionAction", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.StudyUser", "AuditUserID", c => c.String());
            AddColumn("dbo.StudyUser", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.StudyUser", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.ReferenceMaterial", "AuditUserID", c => c.String());
            AddColumn("dbo.ReferenceMaterial", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.ReferenceMaterial", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.StudyUserRole", "AuditUserID", c => c.String());
            AddColumn("dbo.StudyUserRole", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.StudyUserRole", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.Site", "AuditUserID", c => c.String());
            AddColumn("dbo.Site", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.Site", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.Export", "AuditUserID", c => c.String());
            AddColumn("dbo.Export", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.Export", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SiteLanguage", "AuditUserID", c => c.String());
            AddColumn("dbo.SiteLanguage", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SiteLanguage", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SoftwareRelease", "AuditUserID", c => c.String());
            AddColumn("dbo.SoftwareRelease", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SoftwareRelease", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SoftwareVersion", "AuditUserID", c => c.String());
            AddColumn("dbo.SoftwareVersion", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SoftwareVersion", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.StudyUserWidget", "AuditUserID", c => c.String());
            AddColumn("dbo.StudyUserWidget", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.StudyUserWidget", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.Widget", "AuditUserID", c => c.String());
            AddColumn("dbo.Widget", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.Widget", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.StudyRoleWidget", "AuditUserID", c => c.String());
            AddColumn("dbo.StudyRoleWidget", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.StudyRoleWidget", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.WidgetCount", "AuditUserID", c => c.String());
            AddColumn("dbo.WidgetCount", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.WidgetCount", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.WidgetLink", "AuditUserID", c => c.String());
            AddColumn("dbo.WidgetLink", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.WidgetLink", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.WidgetSystemAction", "AuditUserID", c => c.String());
            AddColumn("dbo.WidgetSystemAction", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.WidgetSystemAction", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SystemAction", "AuditUserID", c => c.String());
            AddColumn("dbo.SystemAction", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SystemAction", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SystemActionStudyRole", "AuditUserID", c => c.String());
            AddColumn("dbo.SystemActionStudyRole", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SystemActionStudyRole", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.CorrectionHistory", "AuditUserID", c => c.String());
            AddColumn("dbo.CorrectionHistory", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CorrectionHistory", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("config.CorrectionStatus", "AuditUserID", c => c.String());
            AddColumn("config.CorrectionStatus", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("config.CorrectionStatus", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.CorrectionWorkflow", "AuditUserID", c => c.String());
            AddColumn("dbo.CorrectionWorkflow", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CorrectionWorkflow", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.Device", "AuditUserID", c => c.String());
            AddColumn("dbo.Device", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.Device", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.DeviceData", "AuditUserID", c => c.String());
            AddColumn("dbo.DeviceData", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.DeviceData", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SyncLog", "AuditUserID", c => c.String());
            AddColumn("dbo.SyncLog", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SyncLog", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.PatientAttribute", "AuditUserID", c => c.String());
            AddColumn("dbo.PatientAttribute", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.PatientAttribute", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.PatientVisit", "AuditUserID", c => c.String());
            AddColumn("dbo.PatientVisit", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.PatientVisit", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("config.MissedVisitReason", "AuditUserID", c => c.String());
            AddColumn("config.MissedVisitReason", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("config.MissedVisitReason", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SecurityQuestion", "AuditUserID", c => c.String());
            AddColumn("dbo.SecurityQuestion", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SecurityQuestion", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.DataApproval", "AuditUserID", c => c.String());
            AddColumn("dbo.DataApproval", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.DataApproval", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.DCFRequest", "AuditUserID", c => c.String());
            AddColumn("dbo.DCFRequest", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.DCFRequest", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.DeviceSession", "AuditUserID", c => c.String());
            AddColumn("dbo.DeviceSession", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.DeviceSession", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("config.EmailContent", "AuditUserID", c => c.String());
            AddColumn("config.EmailContent", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("config.EmailContent", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.EmailContentStudyRole", "AuditUserID", c => c.String());
            AddColumn("dbo.EmailContentStudyRole", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.EmailContentStudyRole", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.EmailRecipient", "AuditUserID", c => c.String());
            AddColumn("dbo.EmailRecipient", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.EmailRecipient", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.EmailSent", "AuditUserID", c => c.String());
            AddColumn("dbo.EmailSent", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.EmailSent", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.InputFieldTypeResult", "AuditUserID", c => c.String());
            AddColumn("dbo.InputFieldTypeResult", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.InputFieldTypeResult", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.QuestionInputFieldTypeResult", "AuditUserID", c => c.String());
            AddColumn("dbo.QuestionInputFieldTypeResult", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.QuestionInputFieldTypeResult", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.NotificationRequest", "AuditUserID", c => c.String());
            AddColumn("dbo.NotificationRequest", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.NotificationRequest", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.ReportStudyRole", "AuditUserID", c => c.String());
            AddColumn("dbo.ReportStudyRole", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.ReportStudyRole", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.ScreenReportDialog", "AuditUserID", c => c.String());
            AddColumn("dbo.ScreenReportDialog", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.ScreenReportDialog", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SoftwareReleaseCountry", "AuditUserID", c => c.String());
            AddColumn("dbo.SoftwareReleaseCountry", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SoftwareReleaseCountry", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SoftwareReleaseDeviceType", "AuditUserID", c => c.String());
            AddColumn("dbo.SoftwareReleaseDeviceType", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SoftwareReleaseDeviceType", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.StudyRoleUpdate", "AuditUserID", c => c.String());
            AddColumn("dbo.StudyRoleUpdate", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.StudyRoleUpdate", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.SystemSetting", "AuditUserID", c => c.String());
            AddColumn("dbo.SystemSetting", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.SystemSetting", "LastModifiedByDatabaseUser", c => c.String());
            AddColumn("dbo.VisitComplianceReportQuestionnaireType", "AuditUserID", c => c.String());
            AddColumn("dbo.VisitComplianceReportQuestionnaireType", "LastModified", c => c.DateTime(nullable: false));
            AddColumn("dbo.VisitComplianceReportQuestionnaireType", "LastModifiedByDatabaseUser", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.VisitComplianceReportQuestionnaireType", "LastModifiedByDatabaseUser");
            DropColumn("dbo.VisitComplianceReportQuestionnaireType", "LastModified");
            DropColumn("dbo.VisitComplianceReportQuestionnaireType", "AuditUserID");
            DropColumn("dbo.SystemSetting", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SystemSetting", "LastModified");
            DropColumn("dbo.SystemSetting", "AuditUserID");
            DropColumn("dbo.StudyRoleUpdate", "LastModifiedByDatabaseUser");
            DropColumn("dbo.StudyRoleUpdate", "LastModified");
            DropColumn("dbo.StudyRoleUpdate", "AuditUserID");
            DropColumn("dbo.SoftwareReleaseDeviceType", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SoftwareReleaseDeviceType", "LastModified");
            DropColumn("dbo.SoftwareReleaseDeviceType", "AuditUserID");
            DropColumn("dbo.SoftwareReleaseCountry", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SoftwareReleaseCountry", "LastModified");
            DropColumn("dbo.SoftwareReleaseCountry", "AuditUserID");
            DropColumn("dbo.ScreenReportDialog", "LastModifiedByDatabaseUser");
            DropColumn("dbo.ScreenReportDialog", "LastModified");
            DropColumn("dbo.ScreenReportDialog", "AuditUserID");
            DropColumn("dbo.ReportStudyRole", "LastModifiedByDatabaseUser");
            DropColumn("dbo.ReportStudyRole", "LastModified");
            DropColumn("dbo.ReportStudyRole", "AuditUserID");
            DropColumn("dbo.NotificationRequest", "LastModifiedByDatabaseUser");
            DropColumn("dbo.NotificationRequest", "LastModified");
            DropColumn("dbo.NotificationRequest", "AuditUserID");
            DropColumn("dbo.QuestionInputFieldTypeResult", "LastModifiedByDatabaseUser");
            DropColumn("dbo.QuestionInputFieldTypeResult", "LastModified");
            DropColumn("dbo.QuestionInputFieldTypeResult", "AuditUserID");
            DropColumn("dbo.InputFieldTypeResult", "LastModifiedByDatabaseUser");
            DropColumn("dbo.InputFieldTypeResult", "LastModified");
            DropColumn("dbo.InputFieldTypeResult", "AuditUserID");
            DropColumn("dbo.EmailSent", "LastModifiedByDatabaseUser");
            DropColumn("dbo.EmailSent", "LastModified");
            DropColumn("dbo.EmailSent", "AuditUserID");
            DropColumn("dbo.EmailRecipient", "LastModifiedByDatabaseUser");
            DropColumn("dbo.EmailRecipient", "LastModified");
            DropColumn("dbo.EmailRecipient", "AuditUserID");
            DropColumn("dbo.EmailContentStudyRole", "LastModifiedByDatabaseUser");
            DropColumn("dbo.EmailContentStudyRole", "LastModified");
            DropColumn("dbo.EmailContentStudyRole", "AuditUserID");
            DropColumn("config.EmailContent", "LastModifiedByDatabaseUser");
            DropColumn("config.EmailContent", "LastModified");
            DropColumn("config.EmailContent", "AuditUserID");
            DropColumn("dbo.DeviceSession", "LastModifiedByDatabaseUser");
            DropColumn("dbo.DeviceSession", "LastModified");
            DropColumn("dbo.DeviceSession", "AuditUserID");
            DropColumn("dbo.DCFRequest", "LastModifiedByDatabaseUser");
            DropColumn("dbo.DCFRequest", "LastModified");
            DropColumn("dbo.DCFRequest", "AuditUserID");
            DropColumn("dbo.DataApproval", "LastModifiedByDatabaseUser");
            DropColumn("dbo.DataApproval", "LastModified");
            DropColumn("dbo.DataApproval", "AuditUserID");
            DropColumn("dbo.SecurityQuestion", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SecurityQuestion", "LastModified");
            DropColumn("dbo.SecurityQuestion", "AuditUserID");
            DropColumn("config.MissedVisitReason", "LastModifiedByDatabaseUser");
            DropColumn("config.MissedVisitReason", "LastModified");
            DropColumn("config.MissedVisitReason", "AuditUserID");
            DropColumn("dbo.PatientVisit", "LastModifiedByDatabaseUser");
            DropColumn("dbo.PatientVisit", "LastModified");
            DropColumn("dbo.PatientVisit", "AuditUserID");
            DropColumn("dbo.PatientAttribute", "LastModifiedByDatabaseUser");
            DropColumn("dbo.PatientAttribute", "LastModified");
            DropColumn("dbo.PatientAttribute", "AuditUserID");
            DropColumn("dbo.SyncLog", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SyncLog", "LastModified");
            DropColumn("dbo.SyncLog", "AuditUserID");
            DropColumn("dbo.DeviceData", "LastModifiedByDatabaseUser");
            DropColumn("dbo.DeviceData", "LastModified");
            DropColumn("dbo.DeviceData", "AuditUserID");
            DropColumn("dbo.Device", "LastModifiedByDatabaseUser");
            DropColumn("dbo.Device", "LastModified");
            DropColumn("dbo.Device", "AuditUserID");
            DropColumn("dbo.CorrectionWorkflow", "LastModifiedByDatabaseUser");
            DropColumn("dbo.CorrectionWorkflow", "LastModified");
            DropColumn("dbo.CorrectionWorkflow", "AuditUserID");
            DropColumn("config.CorrectionStatus", "LastModifiedByDatabaseUser");
            DropColumn("config.CorrectionStatus", "LastModified");
            DropColumn("config.CorrectionStatus", "AuditUserID");
            DropColumn("dbo.CorrectionHistory", "LastModifiedByDatabaseUser");
            DropColumn("dbo.CorrectionHistory", "LastModified");
            DropColumn("dbo.CorrectionHistory", "AuditUserID");
            DropColumn("dbo.SystemActionStudyRole", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SystemActionStudyRole", "LastModified");
            DropColumn("dbo.SystemActionStudyRole", "AuditUserID");
            DropColumn("dbo.SystemAction", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SystemAction", "LastModified");
            DropColumn("dbo.SystemAction", "AuditUserID");
            DropColumn("dbo.WidgetSystemAction", "LastModifiedByDatabaseUser");
            DropColumn("dbo.WidgetSystemAction", "LastModified");
            DropColumn("dbo.WidgetSystemAction", "AuditUserID");
            DropColumn("dbo.WidgetLink", "LastModifiedByDatabaseUser");
            DropColumn("dbo.WidgetLink", "LastModified");
            DropColumn("dbo.WidgetLink", "AuditUserID");
            DropColumn("dbo.WidgetCount", "LastModifiedByDatabaseUser");
            DropColumn("dbo.WidgetCount", "LastModified");
            DropColumn("dbo.WidgetCount", "AuditUserID");
            DropColumn("dbo.StudyRoleWidget", "LastModifiedByDatabaseUser");
            DropColumn("dbo.StudyRoleWidget", "LastModified");
            DropColumn("dbo.StudyRoleWidget", "AuditUserID");
            DropColumn("dbo.Widget", "LastModifiedByDatabaseUser");
            DropColumn("dbo.Widget", "LastModified");
            DropColumn("dbo.Widget", "AuditUserID");
            DropColumn("dbo.StudyUserWidget", "LastModifiedByDatabaseUser");
            DropColumn("dbo.StudyUserWidget", "LastModified");
            DropColumn("dbo.StudyUserWidget", "AuditUserID");
            DropColumn("dbo.SoftwareVersion", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SoftwareVersion", "LastModified");
            DropColumn("dbo.SoftwareVersion", "AuditUserID");
            DropColumn("dbo.SoftwareRelease", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SoftwareRelease", "LastModified");
            DropColumn("dbo.SoftwareRelease", "AuditUserID");
            DropColumn("dbo.SiteLanguage", "LastModifiedByDatabaseUser");
            DropColumn("dbo.SiteLanguage", "LastModified");
            DropColumn("dbo.SiteLanguage", "AuditUserID");
            DropColumn("dbo.Export", "LastModifiedByDatabaseUser");
            DropColumn("dbo.Export", "LastModified");
            DropColumn("dbo.Export", "AuditUserID");
            DropColumn("dbo.Site", "LastModifiedByDatabaseUser");
            DropColumn("dbo.Site", "LastModified");
            DropColumn("dbo.Site", "AuditUserID");
            DropColumn("dbo.StudyUserRole", "LastModifiedByDatabaseUser");
            DropColumn("dbo.StudyUserRole", "LastModified");
            DropColumn("dbo.StudyUserRole", "AuditUserID");
            DropColumn("dbo.ReferenceMaterial", "LastModifiedByDatabaseUser");
            DropColumn("dbo.ReferenceMaterial", "LastModified");
            DropColumn("dbo.ReferenceMaterial", "AuditUserID");
            DropColumn("dbo.StudyUser", "LastModifiedByDatabaseUser");
            DropColumn("dbo.StudyUser", "LastModified");
            DropColumn("dbo.StudyUser", "AuditUserID");
            DropColumn("dbo.CorrectionAction", "LastModifiedByDatabaseUser");
            DropColumn("dbo.CorrectionAction", "LastModified");
            DropColumn("dbo.CorrectionAction", "AuditUserID");
            DropColumn("dbo.CorrectionDiscussion", "LastModifiedByDatabaseUser");
            DropColumn("dbo.CorrectionDiscussion", "LastModified");
            DropColumn("dbo.CorrectionDiscussion", "AuditUserID");
            DropColumn("dbo.CorrectionApprovalDataAdditional", "LastModifiedByDatabaseUser");
            DropColumn("dbo.CorrectionApprovalDataAdditional", "LastModified");
            DropColumn("dbo.CorrectionApprovalDataAdditional", "AuditUserID");
            DropColumn("dbo.CorrectionApprovalData", "LastModifiedByDatabaseUser");
            DropColumn("dbo.CorrectionApprovalData", "LastModified");
            DropColumn("dbo.CorrectionApprovalData", "AuditUserID");
            DropColumn("dbo.Correction", "LastModifiedByDatabaseUser");
            DropColumn("dbo.Correction", "LastModified");
            DropColumn("dbo.Correction", "AuditUserID");
            DropColumn("dbo.Patient", "LastModifiedByDatabaseUser");
            DropColumn("dbo.Patient", "LastModified");
            DropColumn("dbo.Patient", "AuditUserID");
            DropColumn("dbo.CareGiver", "LastModifiedByDatabaseUser");
            DropColumn("dbo.CareGiver", "LastModified");
            DropColumn("dbo.CareGiver", "AuditUserID");
            DropColumn("dbo.DiaryEntry", "LastModifiedByDatabaseUser");
            DropColumn("dbo.DiaryEntry", "LastModified");
            DropColumn("dbo.DiaryEntry", "AuditUserID");
            DropColumn("dbo.AnswerScore", "LastModifiedByDatabaseUser");
            DropColumn("dbo.AnswerScore", "LastModified");
            DropColumn("dbo.AnswerScore", "AuditUserID");
            DropColumn("dbo.Answer", "LastModifiedByDatabaseUser");
            DropColumn("dbo.Answer", "LastModified");
            DropColumn("dbo.Answer", "AuditUserID");
            DropColumn("dbo.AdditionalTablesToSync", "LastModifiedByDatabaseUser");
            DropColumn("dbo.AdditionalTablesToSync", "LastModified");
            DropColumn("dbo.AdditionalTablesToSync", "AuditUserID");
        }
    }
}
