// <auto-generated />
namespace YPrime.Data.Study.Configurations.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deprecate_software_version__priority_isactive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deprecate_software_version__priority_isactive));
        
        string IMigrationMetadata.Id
        {
            get { return "202102081850360_deprecate_software_version__priority_isactive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
