// <auto-generated />
namespace YPrime.Data.Study.Configurations.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class resolve_53_merge_issue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resolve_53_merge_issue));
        
        string IMigrationMetadata.Id
        {
            get { return "202108241821014_resolve_5-3_merge_issue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
